# Generated by Django 5.1.3 on 2024-11-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("weight", models.FloatField(help_text="Weight in kg")),
                ("height", models.FloatField(help_text="Height in cm")),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gym_frequency",
                    models.PositiveIntegerField(help_text="Gym visits per week"),
                ),
                (
                    "workout_goal",
                    models.CharField(
                        choices=[
                            ("WL", "Weight Loss"),
                            ("MG", "Muscle Gain"),
                            ("TN", "Toning"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "walking_distance_to_gym",
                    models.FloatField(
                        blank=True, help_text="Distance to gym in km", null=True
                    ),
                ),
                (
                    "time_spent_at_gym",
                    models.DurationField(
                        help_text="Average time spent at the gym per session"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="app.userprofile",
                    ),
                ),
            ],
        ),
    ]
