# Generated by Django 5.1.3 on 2024-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWorkoutProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="User's name", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("weight", models.FloatField(help_text="Weight in kg")),
                ("height", models.FloatField(help_text="Height in cm")),
                (
                    "how_many_times_per_week",
                    models.PositiveIntegerField(help_text="Gym visits per week"),
                ),
                (
                    "how_much_time_in_gym",
                    models.DurationField(
                        help_text="Average time spent at the gym per session"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("WL", "Weight Loss"),
                            ("MG", "Muscle Gain"),
                            ("TN", "Toning"),
                        ],
                        help_text="Workout goal",
                        max_length=2,
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        blank=True,
                        help_text="Focused body part (e.g., arms, legs, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="workoutsession",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="WorkoutSession",
        ),
    ]
