# Generated by Django 5.1.3 on 2024-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_userworkoutprofile_how_many_times_per_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userworkoutprofile",
            name="how_many_times_per_week",
            field=models.PositiveIntegerField(
                blank=True, help_text="Gym visits per week", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userworkoutprofile",
            name="how_much_time_in_gym",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Average time spent at the gym per session",
                null=True,
            ),
        ),
    ]
